### ISSUE TITLE
MotorcycleIcon

### ISSUE THREAD

**Issue by wendylw** [phosphor-icons/phosphor-home#143] opened 2022-06-16 09:48 UTC
**Describe the requested icon**
Food delivery type

**Screenshots**
![image](https://user-images.githubusercontent.com/4416839/174043711-8a1d92f6-2078-42d8-9875-778b2fb05cfd.png)

**Additional context**
Add any other context here.

**Comment by Ellarddekoeijer** [comment] 2022-06-27 15:13
Yes please, I really need this too!

**Comment by rektdeckard** [comment] 2022-07-02 23:00
Duplicate of #137

**Closed by rektdeckard** 2022-07-02 23:00 UTC
Labels: enhancement

**Comment by rektdeckard** [comment] 2023-03-10 01:12
Added `motorcycle`, `moped`, `moped-front`, `scooter` in v2.0.0
